-- 코드를 입력하세요
SELECT C.AUTHOR_ID, A.AUTHOR_NAME, C.CATEGORY, SUM(C.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A JOIN (
SELECT B.AUTHOR_ID, B.CATEGORY, ((S.SALES) * B.PRICE) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
# GROUP BY B.BOOK_ID
) C
ON A.AUTHOR_ID = C.AUTHOR_ID
GROUP BY 1, 2, 3
ORDER BY 1, 3 DESC
